export enum OfferStatus {
  DRAFT = 'DRAFT',
  OFFER_PENDING = 'OFFER_PENDING',
  L1_PENDING = 'L1_PENDING',
  L2_PENDING = 'L2_PENDING',
  SALESMEN_CLOSED = 'SALESMEN_CLOSED',
  CLOSED_BY_SYSTEM = 'CLOSED_BY_SYSTEM',
  L1_REJECTED = 'L1_REJECTED',
  L2_REJECTED = 'L2_REJECTED',
  CUSTOMER_ACCEPTED = 'CUSTOMER_ACCEPTED',
  OFFER_APPROVED = 'OFFER_APPROVED',
  CONCLUDED = 'CONCLUDED',
}
